<?php

/* 
 *      THIS FILE WILL BE USED FOR INSERTING THE QUESTIONS IN THE DATABASE
 *      DEPENDING ON THE MODAL TYPE THE APPROPRIATE FUNCTION WILL BE CALLLED 
 *      AND THE QUERY WILL BE EXECUTED.
 */

//print_r( $_POST);

